In [1]:
import pandas as pd
import numpy as np


In [3]:
df=pd.read_csv("winequality.csv")

In [31]:
df.head(3)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [5]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [9]:
print("Mean:",np.mean(df["chlorides"]))
print("Median:",np.median(df["chlorides"]))
print("Standard Deviation:",np.std(df["chlorides"]))
print("Variance:",np.var(df["chlorides"]))

Mean: 0.08746654158849279
Median: 0.079
Standard Deviation: 0.04705058260331576
Variance: 0.0022137573233114395


In [10]:
arr=df.to_numpy()
print(arr[0:2])

[[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
   0.56    9.4     5.    ]
 [ 7.8     0.88    0.      2.6     0.098  25.     67.      0.9968  3.2
   0.68    9.8     5.    ]]


In [15]:
arr

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [11]:
print(arr[3:5])

[[11.2     0.28    0.56    1.9     0.075  17.     60.      0.998   3.16
   0.58    9.8     6.    ]
 [ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
   0.56    9.4     5.    ]]


In [12]:
print(arr[1])

[ 7.8     0.88    0.      2.6     0.098  25.     67.      0.9968  3.2
  0.68    9.8     5.    ]


In [13]:
print(arr[0,1])

0.7


In [14]:
for i in range(len(arr)):
    print(arr[i])

[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
  0.56    9.4     5.    ]
[ 7.8     0.88    0.      2.6     0.098  25.     67.      0.9968  3.2
  0.68    9.8     5.    ]
[7.80e+00 7.60e-01 4.00e-02 2.30e+00 9.20e-02 1.50e+01 5.40e+01 9.97e-01
 3.26e+00 6.50e-01 9.80e+00 5.00e+00]
[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]
[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
  0.56    9.4     5.    ]
[ 7.4     0.66    0.      1.8     0.075  13.     40.      0.9978  3.51
  0.56    9.4     5.    ]
[ 7.9     0.6     0.06    1.6     0.069  15.     59.      0.9964  3.3
  0.46    9.4     5.    ]
[ 7.3     0.65    0.      1.2     0.065  15.     21.      0.9946  3.39
  0.47   10.      7.    ]
[ 7.8     0.58    0.02    2.      0.073   9.     18.      0.9968  3.36
  0.57    9.5     7.    ]
[7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
 9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]
[ 6

[ 6.7     0.46    0.24    1.7     0.077  18.     34.      0.9948  3.39
  0.6    10.6     6.    ]
[ 6.5     0.52    0.11    1.8     0.073  13.     38.      0.9955  3.34
  0.52    9.3     5.    ]
[7.4000e+00 6.0000e-01 2.6000e-01 2.1000e+00 8.3000e-02 1.7000e+01
 9.1000e+01 9.9616e-01 3.2900e+00 5.6000e-01 9.8000e+00 6.0000e+00]
[7.4000e+00 6.0000e-01 2.6000e-01 2.1000e+00 8.3000e-02 1.7000e+01
 9.1000e+01 9.9616e-01 3.2900e+00 5.6000e-01 9.8000e+00 6.0000e+00]
[ 7.8      0.87     0.26     3.8      0.107   31.      67.       0.99668
  3.26     0.46     9.2      5.     ]
[ 8.4      0.39     0.1      1.7      0.075    6.      25.       0.99581
  3.09     0.43     9.7      6.     ]
[ 9.1     0.775   0.22    2.2     0.079  12.     48.      0.9976  3.18
  0.51    9.6     5.    ]
[ 7.2      0.835    0.       2.       0.166    4.      11.       0.99608
  3.39     0.52    10.       5.     ]
[6.6000e+00 5.8000e-01 2.0000e-02 2.4000e+00 6.9000e-02 1.9000e+01
 4.0000e+01 9.9387e-01 3.3800e+00 6.600

In [16]:
a=arr[0]
filter_arr=[]
for i in a:
    if i>3:
        filter_arr.append("True")
    else:
        filter_arr.append("False")
print(filter_arr)

['True', 'False', 'False', 'False', 'False', 'True', 'True', 'False', 'True', 'False', 'True', 'True']


In [17]:
print(np.sort(arr[0]))

[ 0.      0.076   0.56    0.7     0.9978  1.9     3.51    5.      7.4
  9.4    11.     34.    ]


In [18]:
a=np.array(df["quality"])
b=np.array(df["quality"])
arr=np.concatenate((a,b))
print(arr)

[5 5 5 ... 6 5 6]


In [19]:
print(np.array(df["quality"][0:10]).reshape(5,2))

[[5 5]
 [5 6]
 [5 5]
 [5 7]
 [7 5]]


In [21]:
print("Mean:",df.mean())


Mean: fixed acidity            8.319637
volatile acidity         0.527821
citric acid              0.270976
residual sugar           2.538806
chlorides                0.087467
free sulfur dioxide     15.874922
total sulfur dioxide    46.467792
density                  0.996747
pH                       3.311113
sulphates                0.658149
alcohol                 10.422983
quality                  5.636023
dtype: float64


In [32]:
print("Standard Deviation:\n",df.std())


Standard Deviation:
 fixed acidity            1.741096
volatile acidity         0.179060
citric acid              0.194801
residual sugar           1.409928
chlorides                0.047065
free sulfur dioxide     10.460157
total sulfur dioxide    32.895324
density                  0.001887
pH                       0.154386
sulphates                0.169507
alcohol                  1.065668
quality                  0.807569
dtype: float64


In [33]:
print("Var:\n",df.var())


Var:
 fixed acidity              3.031416
volatile acidity           0.032062
citric acid                0.037947
residual sugar             1.987897
chlorides                  0.002215
free sulfur dioxide      109.414884
total sulfur dioxide    1082.102373
density                    0.000004
pH                         0.023835
sulphates                  0.028733
alcohol                    1.135647
quality                    0.652168
dtype: float64


In [24]:
print("Median:",df.median())

Median: fixed acidity            7.90000
volatile acidity         0.52000
citric acid              0.26000
residual sugar           2.20000
chlorides                0.07900
free sulfur dioxide     14.00000
total sulfur dioxide    38.00000
density                  0.99675
pH                       3.31000
sulphates                0.62000
alcohol                 10.20000
quality                  6.00000
dtype: float64


In [25]:
print(df.iloc[0:4])

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  


In [26]:
df[0:10]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [29]:
print(df["pH"].sort_values())

151     2.74
544     2.86
614     2.87
440     2.88
1470    2.88
        ... 
95      3.85
45      3.90
695     3.90
1316    4.01
1321    4.01
Name: pH, Length: 1599, dtype: float64


In [30]:
a=["A","B","C","D","E","F"]
so=pd.Series(a)
ar=so.values
print("Reshaped Array:\n",ar.reshape((2,3)))

Reshaped Array:
 [['A' 'B' 'C']
 ['D' 'E' 'F']]
